import { createAsyncThunk, createSlice } from "@reduxjs/toolkit";
import { RootState } from "../store";
import { TemplateInterface } from "../../core/Models/Template";
import { TemplatesService } from "../../core/Services/TemplatesService";

export interface TemplateLoadingState {
  templates: TemplateInterface[];
  status: "idle" | "loading" | "failed";
  status_message: string | null;
}

const initialState: TemplateLoadingState = {
  templates: [],
  status: "idle",
  status_message: null,
};

const templatesService = new TemplatesService();

export const loadTemplates = createAsyncThunk(
  "template/loading",
  async (data, { rejectWithValue }) => {
    try {
      const response = await templatesService.getTemplates();
      return response;
    } catch (err) {
      return rejectWithValue(err);
    }
  }
);

export const TemplatesStore = createSlice({
  name: "Templatestore",
  initialState,
  // The `reducers` field lets us define reducers and generate associated actions
  reducers: {},
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  extraReducers: (builder) => {
    builder
      .addCase(loadTemplates.pending, (state) => {
        state.status = "loading";
        state.status_message = "loading data...";
      })
      .addCase(loadTemplates.fulfilled, (state, action) => {
        state.status = "idle";
        state.templates = action.payload;
      })
      .addCase(loadTemplates.rejected, (state) => {
        state.status = "failed";
        state.status_message = "Fetching templates  error, try again...";
      });
  },
});

export const getTemplates = (state: RootState) => state.templates;

export default TemplatesStore.reducer;
